<template>
  <div>
    <BannerComp :image="banner" />
    <TabsComp :brands="games" :contents="contents" class="pt-12" />
    <BottomSliderComp :slides="slot" />
  </div>
</template>
  <script>
import BannerComp from "@/components/Banner.vue";
import TabsComp from "@/components/Tabs.vue";
import BottomSliderComp from "@/components/BottomSlider.vue";
export default {
  name: "GamesView",
  components: {
    BannerComp,
    TabsComp,
    BottomSliderComp,
  },
  data: () => ({
    slot: [
      {
        id: 1,
        name: "advant_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/advant.png",
        opt: ["Slot"],
      },
      {
        id: 2,
        name: "pragmatic_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/pragmatic.png",
        opt: [
          "Slot",
          "Buy Free Spin Games",
          "Megaways Game",
          "Classic Slots",
          "All",
        ],
      },
      {
        id: 3,
        name: "habanero_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/habanero.png",
        opt: ["Slot", "Buy Free Spin"],
      },
      {
        id: 4,
        name: "red_tiger_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/red_tiger.png",
        opt: [
          "Slot",
          "Megaways Game",
          "InfiniReels",
          "Power Reels",
          "Clusters",
          "All",
        ],
      },
      {
        id: 5,
        name: "mg_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/mg.png",
        opt: [
          "Slot",
          "Bonus Buy Feature",
          "Megaways Game",
          "Link and Win Games",
          "Fix Jackpot Games",
          "All",
        ],
      },
      {
        id: 6,
        name: "netent_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/netent.png",
        opt: [
          "Slot",
          "Bonus Buy Feature",
          "Megaways Game",
          "Link and Win Games",
          "Fix Jackpot Games",
          "All",
        ],
      },
      {
        id: 7,
        name: "pg_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/pg.png",
        opt: ["Slot"],
      },
      {
        id: 8,
        name: "ag_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/ag.png",
        opt: ["Slot", "Poker", "Others", "King", "Casual", "Table", "All"],
      },
      {
        id: 9,
        name: "spade_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/spade.png",
        opt: ["Slot", "Buy Free Spin"],
      },
      {
        id: 10,
        name: "cq9_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/cq9.png",
        opt: ["Slot"],
      },
      {
        id: 11,
        name: "joker_gaming_games",
        src: "https://static.nukeasset.com/assets/images/vendor/joker_gaming.png",
        opt: [],
      },
      {
        id: 12,
        name: "ygg_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/ygg.png",
        opt: ["Slot"],
      },
      {
        id: 13,
        name: "sbo_slot",
        src: "https://static.nukeasset.com/assets/images/vendor/sbo.png",
        opt: ["Slot"],
      },
    ],
    banner: "https://dummyimage.com/3198x1200/eb9150/ffffff.png",
    games: [
      {
        id: 1,
        name: "pragmatic_game",
        src: "https://static.nukeasset.com/assets/images/vendor/pragmatic.png",
        opt: [
          "BLACKJACK",
          "BACCARAT",
          "BACCARAT NEW",
          "ROULETTE",
          "SCRATCH CARD",
          "ALL",
        ],
        type: "hot",
        url: "",
      },
      {
        id: 2,
        name: "red_tiger_games",
        src: "https://static.nukeasset.com/assets/images/vendor/red_tiger.png",
        opt: ["RNG"],
        type: "hot",
        url: "",
      },
      {
        id: 3,
        name: "netent_games",
        src: "https://static.nukeasset.com/assets/images/vendor/netent.png",
        opt: ["RNG"],
        type: "new",
        url: "",
      },
      {
        id: 4,
        name: "mg_games",
        src: "https://static.nukeasset.com/assets/images/vendor/mg.png",
        opt: ["ARCADE", "VIDEO BINGO", "TABLE GAMES", "ALL"],
        type: "new",
        url: "",
      },
      {
        id: 5,
        name: "habanero_games",
        src: "https://static.nukeasset.com/assets/images/vendor/habanero.png",
        opt: ["ARCADE", "TABLE GAMES", "WAR", "VIDEO POKER", "ROULETTE", "ALL"],
        type: "hot",
        url: "",
      },
      {
        id: 6,
        name: "sbo_games",
        src: "https://static.nukeasset.com/assets/images/vendor/sbo.png",
        opt: [],
        type: "hot",
        url: "",
      },
      {
        id: 7,
        name: "spade_games",
        src: "https://static.nukeasset.com/assets/images/vendor/spade.png",
        opt: ["TABLE", "ARCADE", "FISHING", "ALL"],
        type: "new",
        url: "",
      },
      {
        id: 8,
        name: "cq9_games",
        src: "https://static.nukeasset.com/assets/images/vendor/cq9.png",
        opt: ["TABLE", "ARCADE", "FISH", "ALL"],
        type: "hot",
        url: "",
      },
    ],
    contents: [
      {
        id: 1,
        name: "pragmatic_game",
        brand: "pragmatic_game",
        src: "https://static.nukeasset.com/assets/images/vendor/pragmatic.png",
        opt: [
          "BLACKJACK",
          "BACCARAT",
          "BACCARAT NEW",
          "ROULETTE",
          "SCRATCH CARD",
          "ALL",
        ],
        type: "hot",
        url: "",
      },
      {
        id: 2,
        name: "red_tiger_games",
        brand: "red_tiger_games",
        src: "https://static.nukeasset.com/assets/images/vendor/red_tiger.png",
        opt: ["RNG"],
        type: "hot",
        url: "",
      },
      {
        id: 3,
        name: "netent_games",
        brand: "netent_games",
        src: "https://static.nukeasset.com/assets/images/vendor/netent.png",
        opt: ["RNG"],
        type: "new",
        url: "",
      },
      {
        id: 4,
        name: "mg_games",
        brand: "mg_games",
        src: "https://static.nukeasset.com/assets/images/vendor/mg.png",
        opt: ["ARCADE", "VIDEO BINGO", "TABLE GAMES", "ALL"],
        type: "new",
        url: "",
      },
      {
        id: 5,
        name: "habanero_games",
        brand: "habanero_games",
        src: "https://static.nukeasset.com/assets/images/vendor/habanero.png",
        opt: ["ARCADE", "TABLE GAMES", "WAR", "VIDEO POKER", "ROULETTE", "ALL"],
        type: "hot",
        url: "",
      },
      {
        id: 6,
        name: "sbo_games",
        brand: "sbo_games",
        src: "https://static.nukeasset.com/assets/images/vendor/sbo.png",
        opt: [],
        type: "hot",
        url: "",
      },
      {
        id: 7,
        name: "spade_games",
        brand: "spade_games",
        src: "https://static.nukeasset.com/assets/images/vendor/spade.png",
        opt: ["TABLE", "ARCADE", "FISHING", "ALL"],
        type: "new",
        url: "",
      },
      {
        id: 8,
        name: "cq9_games",
        brand: "cq9_games",
        src: "https://static.nukeasset.com/assets/images/vendor/cq9.png",
        opt: ["TABLE", "ARCADE", "FISH", "ALL"],
        type: "hot",
        url: "",
      },
    ],
  }),
  methods: {},
  mounted() {},
};
</script>
  